config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/auth/kakao', to: 'users/omniauth_callbacks#kakao'
    get '/users/auth/kakao/callback', to: 'users/omniauth_callbacks#kakao_auth'
  end
  
  root 'restaurants#index'
  
  resources :reviews
  
  post '/uploads' => 'reviews#upload_image'
  get 'likes/:restaurant_id' => 'reviews#like_review'
  
  resources :restaurants do
    member do
    
    end
    
    collection do
    
      get '/search_restaurant' => 'restaurants#search_restaurant'
    end
    
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    mount_uploader :image_path,ImageUploader
    
    validates        :res_name,
                     presence: true
    belongs_to       :state
    belongs_to       :district
    belongs_to       :road
    
    has_many         :menus
    has_many         :visiteds
    has_many         :users, through: :visiteds
    has_many         :reviews
    
    def search_restaurant(condition)
        Restaurant.where("res_name LIKE ?","#{condition}%")
    end
 
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    # @tmp1 = 5-@restaurant.reviews.taste_eval
    # @tmp2 = 5-@restaurant.reviews.service_eval
    # @tmp3 = 5-@restaurant.reviews.price_eval
    # p 'mmmmmmmmmmm'
    p @tmp1
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      @restaurant.state_id = 1;
      @restaurant.district_id =1;
      @restaurant.road_id = 1;
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
 #식당 검색
  def search_restaurant
    respond_to do |format|
      if params[:q].strip.empty?
        format.js {render 'no_content'}
      else
        @restaurants = Restaurant.where("res_name LIKE ?","#{params[:q]}%")
        format.js {render 'search_restaurant'}
      end
    end
  end

 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:res_name,:branch_name,:detail_addr,:food_type,:open_hour,
                                         :close_hour,:min_price,:max_price,:phone,:b_number,:image_path)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(restaurant) do |f| %>
   <div class="form-group">
     <%= f.label :식당이름 %>
     <%= f.text_field :res_name, class: "form-control" %> 
  </div>  

   <div class="form-group">
     <%= f.label :지점명 %>
     <%= f.text_field :branch_name, placeholder:"지점이 하나일 경우, 본점으로 입력",class: "form-control" %> 
  </div>
   <div class="form-group">
     <%= f.label :상세주소 %>
     <%= f.text_field :detail_addr, class: "form-control" %> 
  </div>
  
  <div class="form-group">
     <%= f.label :음식종류 %>
     <%= f.text_field :food_type, placeholder:"예)한식,중식,일식,양식,기타",class: "form-control" %> 
  </div>
  

  
  <div class="form-group">
     <%= f.label :open %>
     <%= f.text_area :open_hour, class: "form-control" %> 
  </div>
  
  <div class="form-group">
     <%= f.label :close %>
     <%= f.text_area :close_hour, class: "form-control" %> 
  </div>
  
  <div class="form-group">
     <%= f.label :최소가격 %>
     <%= f.number_field :min_price, class: "form-control" %> 
  </div>

  <div class="form-group">
     <%= f.label :최대가격 %>
     <%= f.number_field :max_price, class: "form-control" %> 
  </div>

  <div class="form-group">
     <%= f.label :전화번호 %>
     <%= f.text_area :phone, class: "form-control" %> 
  </div>  
  
  <div class="form-group">
     <%= f.label :사업자번호 %>
     <%= f.text_area :b_number, class: "form-control" %> 
  </div>
  <div class="form-group">
     <%= f.label :image_path %>
     <%= f.file_field :image_path, class: "form-control" %> 
  </div>
  

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<%= link_to 'New restaurant', new_restaurant_path %>
<h1>공인맛집</h1>

<form class="form-inline my-2 my-lg-0">
  <input class="form-control w-75 p-3 restaurant-title" id= "search_something"type="search" placeholder="Search" aria-label="Search">
 &nbsp;&nbsp;<button class="btn btn-outline-success my-2 my-sm-0" id ="search_btn">Search</button>
</form>

<div class="recomm-restaurant d-flex justify-content-start row">
  
</div>

<hr>
<% if user_signed_in? %>
<!-- 로그인된 상태  -->
<%= current_user.email%>
<%= link_to '로그 아웃', destroy_user_session_path, method: "delete" %>
<% else %>
<!-- 로그아웃된 상태  -->
<%= link_to '로그인', new_user_session_path %>
<%  end %>
<hr>

<script>
  $(document).on('ready',function(){
    $( "#search_btn" ).click(function(e) {
      e.preventDefault();
      var something = $( "#search_something" ).val();
      // $( "#search_something" ).html('');
      console.log(something);
      $.ajax({
        url: '/restaurants/search_restaurant',
        data: {
          q: something
        }
      })
    });
  });
</script>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/search_restaurant.js.erb
console.log("찾음");

 $('.recomm-restaurant').html(`
  <% @restaurants.each do |restaurant| %>
   <div class="card col-md-3">
   <img class="card-img-top" src="<%= restaurant.image_path.thumb.url%>" alt="<%= restaurant.res_name%>">
   <div class="card-body">
    <h5 class="card-title"><span><%= restaurant.res_name%></span></h5>
    <p class="card-text"><%= restaurant.food_type%></p>
    <p class="card-text"><%= restaurant.detail_addr%></p>
    <p class="card-text"><%= restaurant.phone%></p>
    
    <%= link_to '식당 정보보기', restaurant_path(restaurant), class: 'btn btn-primary' %>
  </div>
</div>
<%  end %>
 `);

app/views/restaurants/search_result.html.erb
<div id= "title" class="row">
<% @restaurants.each do |restaurant| %>
<div class="card col-md-3">
  <img class="card-img-top" src="<%= restaurant.image_path.thumb.url%>" alt="<%= restaurant.res_name%>">
  <div class="card-body">
    <h5 class="card-title"><span><%= restaurant.res_name%></span></h5>
    <p class="card-text"><%= restaurant.food_type%></p>
    <p class="card-text"><%= restaurant.detail_addr%></p>
    <p class="card-text"><%= restaurant.phone%></p>
    
    <%= link_to '식당 정보보기', restaurant_path(restaurant), class: 'btn btn-primary' %>
  </div>
</div>
<%  end %>
</div>

app/views/restaurants/show.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>

.wrapper {
  position: relative;
  width: 100%;
  height: 100%;
}

.like {
  cursor: pointer;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  width: 300px;

  
}

.liked {
  color: #F1599E;
}
</style>
<h1 id="title">식당
 <p align = "right">
  <button class= "btn btn-primary">스크랩</button> 
  <%= link_to "리뷰작성", new_review_path(restaurant_id: @restaurant.id),class: "btn btn-secondary"%>
 </p>
</h1>

<hr>

 

<h3>리뷰  목록</h3>
<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item ">
         맛평가 : 
          <% (1..review.taste_eval).each do%>
              <span class="fa fa-star checked" style="width:11px; margin-top:-5px; font-size:9px; color:#FFD700;"></span>
          <%end%>
          <% tmp = 5- review.taste_eval%>
          <% (1..tmp).each do %>
            <span class="fa fa-star" style="width:11px; margin-top:-5px; font-size:9px; color:#808080;"></span>
          <% end %>
          &nbsp;&nbsp;
          서비스평가 :
          <% (1..review.service_eval).each do%>
              <span  class="fa fa-star checked" style="width:11px; margin-top:-5px; font-size:9px; color:#FFD700;"></span>
          <%end%>
          <% tmp = 5- review.service_eval%>
          <% (1..tmp).each do %>
            <span class="fa fa-star" style="width:11px; margin-top:-5px; font-size:9px; color:#808080;"></span>
          <% end %>
          &nbsp;&nbsp;
          가격평가 : 
           <% (1..review.price_eval).each do%>
              <span  class="fa fa-star checked" style=" width:11px; margin-top:-5px; font-size:9px; color:#FFD700;"></span>
          <%end%>
          <% tmp = 5- review.price_eval%>
          <% (1..tmp).each do %>
            <span class="fa fa-star" style="width:11px; margin-top:-5px; font-size:9px; color:#808080;"></span>
          <% end %>
          
  
      <br><p><%= simple_format(review.contents) %></p>
      <p align="right">
        <% if @user_likes_review.nil? %>
          <div class="wrapper">
            <div class="like">
              <span class="heart">❤</span> 
               <span class="count"></span>
            </div>
          </div>
         <!--(<span class="like-count"><%=review.likes.count%></span>)-->
        <% else %>  
          <button class="btn btn-warning text-white like">좋아요 취소(<span class="like-count"><%=review.likes.count%></span>)</button>
        <% end %> 
      </p>
      
      
      </li>
  <% end %>
</ul>



<hr>
<% if user_signed_in? %>
<!-- 로그인된 상태  -->
<%= link_to "#{current_user.email}" %>
<%= link_to '로그 아웃', destroy_user_session_path, method: "delete" %>
<% else %>
<!-- 로그아웃된 상태  -->
<%= link_to '로그인', new_user_session_path %>
<%  end %>




<script>
$(document).ready(function(){
  
  var $like = $('.like'),
      $count = $('.count'),
      $liked = false;
  

  var $randNum = 0;
  $count.text($randNum);
  
  $like.on('click', function(){
    console.log($liked);
    if(!$liked) {
        $(this).addClass('liked');
        $count.text($randNum + 1);
        $liked = true;
    } else {
        $(this).removeClass('liked');
        $count.text($randNum);
        $liked = false;
    }
    
  });
});
  
</script>