config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/auth/kakao', to: 'users/omniauth_callbacks#kakao'
    get '/users/auth/kakao/callback', to: 'users/omniauth_callbacks#kakao_auth'
  end
  
  root 'restaurants#index'
  
  resources :reviews
  
  post '/uploads' => 'reviews#upload_image'
  get 'likes/:restaurant_id' => 'reviews#like_review'
  
  resources :restaurants do
    member do
    
    end
    
    collection do
    
      get '/search_restaurant' => 'restaurants#search_restaurant'
    end
    
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :js_authenticate_user!, only: [:like_review]
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @user_likes_review = Like.where(user_id: current_user.id, review_id: @review.id).first if user_signed_in?
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    
    #유저는 한 식당에 한번의 리뷰만 쓸 수 있다.
    # if current_user.reviews.restaurant_id?
    #   redirect_to @review.errors,flash:{note: '리뷰는 한번만.'}
    # else
    #   @review.save
    #   redirect_to @review,flash:{success: 'Review was successfully created.'}
    # end
      
    if @review.save
      redirect_to @review, flash:{success: 'Review was successfully created.'}
    else
      render :new
    end
    
    
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #summer note - upload image
  def upload_image
    @image = Image.create(image_path: params[:upload][:image])
    p @image
    render json: @image
  end
  
  
  # 리뷰 좋아요
  def like_review
    p params
    #현재 유저와 params에 담긴 movie 간의
    #좋아요 관계를 설정한다.
      
    #where의 결과값은 배열이다.
    #따라서 .first를 이용해 맨 앞 한가지만.
    @like = Like.where(user_id: current_user.id,review_id: params[:review_id]).first
  
    if @like.nil?
      #새로 누른 경우
      #좋아요 관계 설정
      @like = Like.create(user_id: current_user.id,review_id: params[:review_id])
      puts "좋아요 설정 끝"
    else
      #만약에 현재 로그인한 유저가 이미 좋아요를 눌렀을 경우
      #해당 Like 인스턴스 삭제
      @like.destroy
    end
    puts @like.frozen?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:title, :taste_eval,:price_eval,:service_eval,:contents, :restaurant_id,:image_path)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
.checked {
    color: orange;
}
@import url(//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css);

fieldset, label { margin: 0; padding: 0; }
body{ margin: 20px; }
h1 { font-size: 1.5em; margin: 10px; }

/****** Style Star Rating Widget *****/

.rating { 
  border: none;
  float: left;
}

.rating > input { display: none; } 
.rating > label:before { 
  margin: 5px;
  font-size: 1.25em;
  font-family: FontAwesome;
  display: inline-block;
  content: "\f005";
}

.rating > .half:before { 
  content: "\f089";
  position: absolute;
}

.rating > label { 
  color: #ddd; 
 float: right; 
}

/***** CSS Magic to Highlight Stars on Hover *****/

.rating > input:checked ~ label, /* show gold star when clicked */
.rating:not(:checked) > label:hover, /* hover current star */
.rating:not(:checked) > label:hover ~ label { color: #FFD700;  } /* hover previous stars in list */

.rating > input:checked + label:hover, /* hover current star when changing rating */
.rating > input:checked ~ label:hover,
.rating > label:hover ~ input:checked ~ label, /* lighten current selection */
.rating > input:checked ~ label:hover ~ label { color: #FFED85;  } 



/*****Star rating 2 *****/
.rating2 { 
  border: none;
  float: left;
}

.rating2 > input { display: none; } 
.rating2 > label:before { 
  margin: 5px;
  font-size: 1.25em;
  font-family: FontAwesome;
  display: inline-block;
  content: "\f005";
}

.rating2 > .half:before { 
  content: "\f089";
  position: absolute;
}

.rating2 > label { 
  color: #ddd; 
 float: right; 
}

/***** CSS Magic to Highlight Stars on Hover *****/

.rating2 > input:checked ~ label, /* show gold star when clicked */
.rating2:not(:checked) > label:hover, /* hover current star */
.rating2:not(:checked) > label:hover ~ label { color: #FFD700;  } /* hover previous stars in list */

.rating2 > input:checked + label:hover, /* hover current star when changing rating */
.rating2 > input:checked ~ label:hover,
.rating2 > label:hover ~ input:checked ~ label, /* lighten current selection */
.rating2 > input:checked ~ label:hover ~ label { color: #FFED85;  } 

/*****Star rating 3 *****/
.rating3 { 
  border: none;
  float: left;
}

.rating3 > input { display: none; } 
.rating3 > label:before { 
  margin: 5px;
  font-size: 1.25em;
  font-family: FontAwesome;
  display: inline-block;
  content: "\f005";
}

.rating3 > .half:before { 
  content: "\f089";
  position: absolute;
}

.rating3 > label { 
  color: #ddd; 
 float: right; 
}

/***** CSS Magic to Highlight Stars on Hover *****/

.rating3 > input:checked ~ label, /* show gold star when clicked */
.rating3:not(:checked) > label:hover, /* hover current star */
.rating3:not(:checked) > label:hover ~ label { color: #FFD700;  } /* hover previous stars in list */

.rating3 > input:checked + label:hover, /* hover current star when changing rating */
.rating3 > input:checked ~ label:hover,
.rating3 > label:hover ~ input:checked ~ label, /* lighten current selection */
.rating3 > input:checked ~ label:hover ~ label { color: #FFED85;  } 

</style>


<%= form_for(review) do |f| %>

    <%= f.hidden_field :restaurant_id, value: params[:restaurant_id] %>
    
    <div class="field">
      <%= f.label :맛평가 %>
      
      <fieldset class="rating taste_eval">
          <input type="radio" id="star1-5" name="review[taste_eval]" value="5" /><label class = "full" for="star1-5" title="Awesome - 5 stars"></label>
          <input type="radio" id="star1-4" name="review[taste_eval]" value="4" /><label class = "full" for="star1-4" title="Pretty good - 4 stars"></label>
          <input type="radio" id="star1-3" name="review[taste_eval]" value="3" /><label class = "full" for="star1-3" title="Meh - 3 stars"></label>
          <input type="radio" id="star1-2" name="review[taste_eval]" value="2" /><label class = "full" for="star1-2" title="Kinda bad - 2 stars"></label>
          <input type="radio" id="star1-1" name="review[taste_eval]" value="1" /><label class = "full" for="star1-1" title="Sucks big time - 1 star"></label>
      </fieldset> 
    </div><br>
    
    <div class="field">
      <%= f.label :가격평가 %>
      <fieldset class="rating2">
          <input type="radio" id="star5" name="review[price_eval]" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
          <input type="radio" id="star4" name="review[price_eval]" value="4" /><label class = "full" for="star4" title="Pretty good - 4 stars"></label>
          <input type="radio" id="star3" name="review[price_eval]" value="3" /><label class = "full" for="star3" title="Meh - 3 stars"></label>
          <input type="radio" id="star2" name="review[price_eval]" value="2" /><label class = "full" for="star2" title="Kinda bad - 2 stars"></label>
          <input type="radio" id="star1" name="review[price_eval]" value="1" /><label class = "full" for="star1" title="Sucks big time - 1 star"></label>
      </fieldset> 
    </div><br>
    
 
    
    
    <div class="field">
      <%= f.label :서비스평가 %>
      <!--<%= f.number_field :service_eval, class: 'form-control'%>-->
      <fieldset class="rating3">
          <input type="radio" id="star3-5" name="review[service_eval]" value="5" /><label class = "full" for="star3-5" title="Awesome - 5 stars"></label>
          <input type="radio" id="star3-4" name="review[service_eval]" value="4" /><label class = "full" for="star3-4" title="Pretty good - 4 stars"></label>
          <input type="radio" id="star3-3" name="review[service_eval]" value="3" /><label class = "full" for="star3-3" title="Meh - 3 stars"></label>
          <input type="radio" id="star3-2" name="review[service_eval]" value="2" /><label class = "full" for="star3-2" title="Kinda bad - 2 stars"></label>
          <input type="radio" id="star3-1" name="review[service_eval]" value="1" /><label class = "full" for="star3-1" title="Sucks big time - 1 star"></label>
      </fieldset> 
    </div><br>
  
    <div class="form-group">
      <!--<%= f.label :contents %>-->
      <%= f.text_area :contents, 'data-provider': :summernote %>
    </div>

     <br><br> 
    <div class="actions text-right">
      <%= f.submit '작성하기',class: 'btn btn-info'%>
      <%= link_to '뒤로가기', reviews_path,class: 'btn btn-warning text-white' %>
    </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/like_review.js.erb
alert("좋아요가 설정되었습니다.");

var like_count = parseInt($('.like-count').text());

//좋아요가 취소된 경우
// 좋아요 취소버튼 -> 좋아요 버튼으로
if(<%=@like.frozen? %>) {
    like_count = like_count  - 1;
    $('.like').html(`좋아요(<span class='like-count'>${like_count}</span>)`).removeClass("btn-warning text-white").addClass("btn-info");
} else{
//좋아요가 새로 눌린 경우
//좋아요 버튼 -> 좋아요 취소버튼으로
    like_count = like_count  + 1;
    $('.like').html(`좋아요 취소(<span class='like-count'>${like_count}</span>)`).removeClass("btn-info").addClass("btn-warning text-white");
}

<!--console.log(like-count);-->

app/views/reviews/new.html.erb
<h1>식당이름</h1>

<%= render 'form', review: @review %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to '목록으로', restaurant_path(@review.restaurant_id) %>